services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
        - "8888:8888"
    networks:
      - postgres
  discovery-service:
    image: discovery-service
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - postgres
    depends_on:
      - config-server
    restart: unless-stopped
  gateway-service:
    image: gateway-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    networks:
      - postgres
    depends_on:
      - config-server
    restart: unless-stopped
  car-service:
    image: rating-service
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - postgres
    depends_on:
      - postgresql
      - config-server
    restart: unless-stopped
  client-service:
    image: rating-service
    build:
      context: ./smarthouse-service
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      - postgres
    depends_on:
      - postgresql
      - config-server
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge



volumes:
  postgres:
  pgadmin: